### ISSUE TITLE
不支持 https 

### ISSUE THREAD

**Issue by naoyeye** [neekey/iciba#25]
在 https 的网页中使用时会报错

![screen shot 2015-03-07 at 11 55 15 am](https://cloud.githubusercontent.com/assets/434428/6539951/e2a48050-c4c0-11e4-91f0-afefde632977.png)

**Comment by naoyeye** [comment]
@neekey fixed。
![screen shot 2015-03-07 at 12 23 28 pm](https://cloud.githubusercontent.com/assets/434428/6540053/c9b26b58-c4c4-11e4-8ee2-d8622969cd74.png)
测试了，没问题。

**Comment by naoyeye** [comment]
刚又发现一个问题，「加入生词本」功能在 https 的网页中无效。

之前我针对 https 网页中无法查词这一 bug 的修复办法是：获取当前 url 中的通信协议是 http 还是 https， 然后把 http(s) 字符串传到对应的 ajax 请求里。这样能做到在 http 网页中查词时，ajax 会请求 http://open.iciba.com/huaci/dict.php?word=buried 这样的 url; 在 https 网页中查词时，则会请求 https://open.iciba.com/huaci/dict.php?word=buried 。

但是这个办法用在 「加入生词本」时就不行了，因为

iciba 那边的加入生词本功能只支持http （http http://scb.iciba.com/aiframe.php?word=buried&t=1425707769391），换做 https （http://scb.iciba.com/aiframe.php?word=buried&t=1425707769391） 便无效。

一会儿我把之前针对「加入生词本」这一部分做的 https 处理代码去掉。我想到的修复办法是自己起一个服务，用来接受此插件发来的请求（不管是 http 还是 https） ，然后再往 iciba 那边发 —— 等于是中间多了一层预处理。

**Comment by neekey** [comment]
https://github.com/neekey/iciba/pull/26
