### ISSUE TITLE
样式问题：popup 中的 搜索 icon 折行了

### ISSUE THREAD

**Issue by naoyeye** [neekey/iciba#27]
![screen shot 2015-03-07 at 12 26 57 pm](https://cloud.githubusercontent.com/assets/434428/6540064/a1e42b56-c4c5-11e4-87f4-467e93a2b342.png)

**Comment by naoyeye** [comment]
![screen shot 2015-03-07 at 12 32 24 pm](https://cloud.githubusercontent.com/assets/434428/6540086/06b7f5da-c4c6-11e4-8b0b-77979b03a3e8.png)

fixed

**Comment by neekey** [comment]
https://github.com/neekey/iciba/pull/26
