### ISSUE TITLE
"Add to my vocabulary" doesn't work.

### ISSUE THREAD

**Issue by leira** [neekey/iciba#31]
I'm using iciba extension 2.1.0 in Chrome 47.0.2526.111 on Mac. I can search words from extension popup or from context menu, both worked fine. The only problem is, when I click the "Add to my vocabulary" button, nothing happens. And I went to iciba website, I confirmed that no new word added to my vocabulary.

What other information is needed?

**Comment by neekey** [comment]
会在 3.0 中解决 https://github.com/neekey/iciba/milestone/3

**Comment by neekey** [comment]
close issue due to it's duplicate to https://github.com/neekey/iciba/issues/36
