### ISSUE TITLE
不能发音的Bug，howler.js ----This request has been blocked; the content must be served over HTTPS.

### ISSUE THREAD

**Issue by foolhorse** [neekey/iciba#33]
从console中看到：
howler.js:938 Mixed Content: The page at 'https://---------' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://res-tts.iciba.com/a/4/c/---------------------.mp3'. This request has been blocked; the content must be served over HTTPS.

**Comment by unioah** [comment]
需要修改Content Security Policy。
我加了一个pull请求

**Comment by neekey** [comment]
thanks for @unioah 's fix https://github.com/neekey/iciba/pull/35
